INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('admin',md5('admin'),'T');
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('guest',md5('guest'),'T');
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user',md5('11'),'T');
UPDATE USERS SET ID=1 WHERE USERNAME='admin';
UPDATE USERS SET ID=2 WHERE USERNAME='guest';
UPDATE USERS SET ID=3 WHERE USERNAME='user';
INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUES (1,'ROLE_ADMIN');
INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUES (1,'ROLE_USER');
INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUES (2,'ROLE_USER');
INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUES (3,'ROLE_USER');

